Algoritmo "EXERCICIO 3"
// 
//  
// Descrição   : V=PI*R^2 * H
// Autor(a)    : MARVIN DE SOUZA SILVA
// Data atual  : 20/3/2021
Var
// Seção de Declarações das variáveis 

raio:real
altura:real
v:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite o raio em metros: ")
leia (raio)
escreva ("digite a altura em metros: ")
leia (altura)
v<-(3.14 *altura * (raio^2))
escreva ("Volume e igual a " ,v, "m cubicos. ")
Fimalgoritmo